seed_everything: 80085
trainer:
  accelerator: gpu
  devices: 4 #2
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: True
  max_epochs: 50
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  check_val_every_n_epoch: 1
  log_every_n_steps: 5
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_center
        mode: min
        save_last: true
        save_top_k: 5
        filename: "model-{epoch:02d}-{val_loss:.2f}-{val_center:.2f}"
